### ISSUE TITLE
error when building fresh project

### ISSUE THREAD

**Issue by bigmistqke** [nativescript-community/solid-js#6]
I get the following error `TypeError: The 'compilation' argument must be an instance of Compilation` when running `ns run android` after a fresh `git clone` and `pnpm install`:

full log:
> TypeError: The 'compilation' argument must be an instance of Compilation
    at NormalModule.getCompilationHooks (/Users/bigmistqke/Documents/GitHub/solid-native2/node_modules/webpack/lib/NormalModule.js:227:10)
    at /Users/bigmistqke/Documents/GitHub/solid-native2/node_modules/webpack/lib/HotModuleReplacementPlugin.js:767:18
    at Hook.eval [as call] (eval at create (/Users/bigmistqke/Documents/GitHub/solid-native2/node_modules/.pnpm/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:102:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/bigmistqke/Documents/GitHub/solid-native2/node_modules/.pnpm/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/bigmistqke/Documents/GitHub/solid-native2/node_modules/.pnpm/@nativescript+webpack@5.0.16_typescript@5.1.6/node_modules/webpack/lib/Compiler.js:1126:26)
    at /Users/bigmistqke/Documents/GitHub/solid-native2/node_modules/.pnpm/@nativescript+webpack@5.0.16_typescript@5.1.6/node_modules/webpack/lib/Compiler.js:1170:29
    at Hook.eval [as callAsync] (eval at create (/Users/bigmistqke/Documents/GitHub/solid-native2/node_modules/.pnpm/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/bigmistqke/Documents/GitHub/solid-native2/node_modules/.pnpm/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Users/bigmistqke/Documents/GitHub/solid-native2/node_modules/.pnpm/@nativescript+webpack@5.0.16_typescript@5.1.6/node_modules/webpack/lib/Compiler.js:1165:28)
    at /Users/bigmistqke/Documents/GitHub/solid-native2/node_modules/.pnpm/@nativescript+webpack@5.0.16_typescript@5.1.6/node_modules/webpack/lib/Watching.js:218:19
    at eval (eval at create (/Users/bigmistqke/Documents/GitHub/solid-native2/node_modules/.pnpm/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /Users/bigmistqke/Documents/GitHub/solid-native2/node_modules/@nativescript/webpack/dist/plugins/WatchStatePlugin.js:22:13
    at Hook.eval [as callAsync] (eval at create (/Users/bigmistqke/Documents/GitHub/solid-native2/node_modules/.pnpm/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/bigmistqke/Documents/GitHub/solid-native2/node_modules/.pnpm/node_modules/tapable/lib/Hook.js:18:14)
    at run (/Users/bigmistqke/Documents/GitHub/solid-native2/node_modules/.pnpm/@nativescript+webpack@5.0.16_typescript@5.1.6/node_modules/webpack/lib/Watching.js:172:33)
    at /Users/bigmistqke/Documents/GitHub/solid-native2/node_modules/.pnpm/@nativescript+webpack@5.0.16_typescript@5.1.6/node_modules/webpack/lib/Watching.js:167:6

**Comment by ammarahm-ed** [comment]
Hey, which example app are you trying to run? Here's a stackblitz with everything latest that works for me: https://stackblitz.com/edit/nativescript-solid-lqmrxv?file=webpack.config.js,package.json,app%2Fcomponent.jsx,app%2Fapp.jsx

You can  also run this locally by just downloading it.

**Comment by bigmistqke** [comment]
for documentation purposes: the issue was using `pnpm`, with `npm install --legacy-peer-deps` it works.
